# Generated by Django 5.2.11 on 2026-02-23 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_categorymodel_sugested_limit_and_more'),
        ('Goals', '0002_alter_goalmodel_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetmodel',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Essencial'), ('MEDIUM', 'Desejável'), ('LOW', 'Supérfluo')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='goalmodel',
            name='account_origin',
            field=models.ForeignKey(blank=True, help_text='Conta principal de onde saem os aportes para esta meta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.accountmodel'),
        ),
        migrations.AddField(
            model_name='goalmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
