# Generated by Django 5.2.11 on 2026-02-10 12:40

import UserAccount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=UserAccount.models.user_directory_path),
        ),
    ]
