# Generated by Django 5.2.11 on 2026-02-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_alter_profilemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Renda mensal fixa utilizada para calcular sugestão de orçamentos', max_digits=10, null=True),
        ),
    ]
