# Generated by Django 5.2.11 on 2026-02-10 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Accounts.categorymodel'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounts.accountmodel'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounts.categorymodel'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='original_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currencymodel'),
        ),
        migrations.AddField(
            model_name='transfermodel',
            name='destination_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='Accounts.accountmodel'),
        ),
        migrations.AddField(
            model_name='transfermodel',
            name='destination_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_destination_currency', to='currencies.currencymodel'),
        ),
        migrations.AddField(
            model_name='transfermodel',
            name='original_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currencymodel'),
        ),
        migrations.AddField(
            model_name='transfermodel',
            name='source_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing', to='Accounts.accountmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='accountmodel',
            unique_together={('user', 'name')},
        ),
    ]
