# Generated by Django 5.2.11 on 2026-02-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_accountmodel_id_alter_categorymodel_id_and_more'),
        ('CreditCard', '0002_alter_creditcardmodel_id_alter_invoicemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CreditCard.creditcardmodel'),
        ),
    ]
