# Generated by Django 5.2.11 on 2026-02-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_transactionmodel_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='sugested_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='type',
            field=models.CharField(choices=[('IN', 'Entrada (Receitas)'), ('OUT', 'Saída (Despesas)')], default='IN', max_length=3),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='type',
            field=models.CharField(choices=[('IN', 'Entrada (Receitas)'), ('OUT', 'Saída (Despesas)')], max_length=3),
        ),
    ]
