# Generated by Django 5.2.11 on 2026-02-23 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_categorymodel_sugested_limit_and_more'),
        ('CreditCard', '0002_alter_creditcardmodel_id_alter_invoicemodel_id'),
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='installments',
            field=models.IntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.CreateModel(
            name='RecurringTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('IN', 'Entrada (Receitas)'), ('OUT', 'Saída (Despesas)')], max_length=3)),
                ('frequency', models.CharField(choices=[('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_execution', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounts.accountmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounts.categorymodel')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CreditCard.creditcardmodel')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currencymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
