# Generated by Django 5.2.11 on 2026-02-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencymodel',
            old_name='simbol',
            new_name='symbol',
        ),
    ]
