# Generated by Django 5.2.11 on 2026-02-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_rename_simbol_currencymodel_symbol'),
        ('currencies', '0003_auto_20260210_0953'),
    ]

    operations = [
    ]
